java_library(
    name = "candle_repository",
    srcs = ["InstrumentRepository.java"],
    visibility = ["//visibility:public"],
    deps = [
        "@tradestar_protos//:instruments_java_proto",
    ],
)
