java_library(
    name = "candle_repository",
    srcs = ["CandleRepository.java"],
    visibility = ["//src/main/java/com/verlumen/tradestar/candles:__subpackages__"],
    deps = [
        "@maven//:com_google_guava_guava",
        "@tradestar_protos//:candles_java_proto",
        "@tradestar_protos//:instruments_java_proto",
    ],
)
